name: Push to GCR GitHub Action
on:
  push:
    tags:
        - "v*.*.*"
        - "V*.*.*"
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test CloudHub.Tests.Unit --verbosity normal

      - name: Extracting Build Environment and Build Id
        id: gitinfo
        run: |
          tag_name=${GITHUB_REF##*/}
          echo "::set-output name=tag_name::${tag_name}"

      - name: Setup gcloud
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }} 
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }} 

      - name: Build/Push docker image
        run: |
            gcloud auth configure-docker
            docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cloudhub_api:${{steps.gitinfo.outputs.tag_name}} .
            docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cloudhub_api:${{steps.gitinfo.outputs.tag_name}}